name: tesspy_env
channels:
  - conda-forge
dependencies:
  - python==3.7
  - sphinx
  - pandoc
  - nbconvert
  - ipykernel
  - nbsphinx
  - sphinx_rtd_theme
  - geopandas
  - osmnx
  - h3-py
  - hdbscan
  - mercantile